/*
 * SPDX-FileCopyrightText: syuilo and misskey-project
 * SPDX-License-Identifier: AGPL-3.0-only
 */

import { Inject, Injectable } from '@nestjs/common';
import { AbstractEndpoint } from '@/server/api/AbstractEndpoint.js';
import { MetaService } from '@/core/MetaService.js';
import type { Config } from '@/config.js';
import { DI } from '@/di-symbols.js';
import { DEFAULT_POLICIES } from '@/core/RoleService.js';
import { z } from 'zod';
import { IdSchema } from '@/models/zod/IdSchema.js';

export const meta = {
	tags: ['meta'],

	requireCredential: true,
	requireAdmin: true,
	kind: 'read:admin:meta',

	res: z.object({
		cacheRemoteFiles: z.boolean().optional(),
		cacheRemoteSensitiveFiles: z.boolean().optional(),
		emailRequiredForSignup: z.boolean().optional(),
		enableHcaptcha: z.boolean().optional(),
		hcaptchaSiteKey: z.string().nullable().optional(),
		enableMcaptcha: z.boolean().optional(),
		mcaptchaSiteKey: z.string().nullable().optional(),
		mcaptchaInstanceUrl: z.string().nullable().optional(),
		enableRecaptcha: z.boolean().optional(),
		recaptchaSiteKey: z.string().nullable().optional(),
		enableTurnstile: z.boolean().optional(),
		turnstileSiteKey: z.string().nullable().optional(),
		swPublickey: z.string().nullable().optional(),
		mascotImageUrl: z.string().nullable().default('/assets/ai.png'),
		bannerUrl: z.string().nullable().optional(),
		serverErrorImageUrl: z.string().nullable().optional(),
		infoImageUrl: z.string().nullable().optional(),
		notFoundImageUrl: z.string().nullable().optional(),
		iconUrl: z.string().nullable().optional(),
		app192IconUrl: z.string().nullable().optional(),
		app512IconUrl: z.string().nullable().optional(),
		enableEmail: z.boolean().optional(),
		enableServiceWorker: z.boolean().optional(),
		translatorAvailable: z.boolean().optional(),
		silencedHosts: z.string().array().optional(),
		pinnedUsers: z.string().array().optional(),
		hiddenTags: z.string().array().optional(),
		blockedHosts: z.string().array().optional(),
		sensitiveWords: z.string().array().optional(),
		prohibitedWords: z.string().array().optional(),
		bannedEmailDomains: z.string().array().optional(),
		preservedUsernames: z.string().array().optional(),
		hcaptchaSecretKey: z.string().nullable().optional(),
		mcaptchaSecretKey: z.string().nullable().optional(),
		recaptchaSecretKey: z.string().nullable().optional(),
		turnstileSecretKey: z.string().nullable().optional(),
		sensitiveMediaDetection: z.string().optional(),
		sensitiveMediaDetectionSensitivity: z.string().optional(),
		setSensitiveFlagAutomatically: z.boolean().optional(),
		enableSensitiveMediaDetectionForVideos: z.boolean().optional(),
		proxyAccountId: IdSchema.nullable().optional(),
		email: z.string().nullable().optional(),
		smtpSecure: z.boolean().optional(),
		smtpHost: z.string().nullable().optional(),
		smtpPort: z.number().nullable().optional(),
		smtpUser: z.string().nullable().optional(),
		smtpPass: z.string().nullable().optional(),
		swPrivateKey: z.string().nullable().optional(),
		useObjectStorage: z.boolean().optional(),
		objectStorageBaseUrl: z.string().nullable().optional(),
		objectStorageBucket: z.string().nullable().optional(),
		objectStoragePrefix: z.string().nullable().optional(),
		objectStorageEndpoint: z.string().nullable().optional(),
		objectStorageRegion: z.string().nullable().optional(),
		objectStoragePort: z.number().nullable().optional(),
		objectStorageAccessKey: z.string().nullable().optional(),
		objectStorageSecretKey: z.string().nullable().optional(),
		objectStorageUseSSL: z.boolean().optional(),
		objectStorageUseProxy: z.boolean().optional(),
		objectStorageSetPublicRead: z.boolean().optional(),
		enableIpLogging: z.boolean().optional(),
		enableActiveEmailValidation: z.boolean().optional(),
		enableVerifymailApi: z.boolean().optional(),
		verifymailAuthKey: z.string().nullable().optional(),
		enableTruemailApi: z.boolean().optional(),
		truemailInstance: z.string().nullable().optional(),
		truemailAuthKey: z.string().nullable().optional(),
		enableChartsForRemoteUser: z.boolean().optional(),
		enableChartsForFederatedInstances: z.boolean().optional(),
		enableServerMachineStats: z.boolean().optional(),
		enableIdenticonGeneration: z.boolean().optional(),
		manifestJsonOverride: z.string().optional(),
		policies: z.record(z.string(), z.unknown()).optional(),
		notesPerOneAd: z.number().optional(),
		backgroundImageUrl: z.string().nullable().optional(),
		deeplAuthKey: z.string().nullable().optional(),
		deeplIsPro: z.boolean().optional(),
		defaultDarkTheme: z.string().nullable().optional(),
		defaultLightTheme: z.string().nullable().optional(),
		description: z.string().nullable().optional(),
		disableRegistration: z.boolean().optional(),
		impressumUrl: z.string().nullable().optional(),
		maintainerEmail: z.string().nullable().optional(),
		maintainerName: z.string().nullable().optional(),
		name: z.string().nullable().optional(),
		shortName: z.string().nullable().optional(),
		objectStorageS3ForcePathStyle: z.boolean().optional(),
		privacyPolicyUrl: z.string().nullable().optional(),
		repositoryUrl: z.string().nullable().optional(),
		summalyProxy: z.string().nullable().optional(),
		themeColor: z.string().nullable().optional(),
		tosUrl: z.string().nullable().optional(),
		uri: z.string().optional(),
		version: z.string().optional(),
	}),
} as const;

export const paramDef = z.object({});

@Injectable()
export default class extends AbstractEndpoint<typeof meta, typeof paramDef> {
	constructor(
		@Inject(DI.config)
		private readonly config: Config,

		private readonly metaService: MetaService,
	) {
		super(meta, paramDef, async () => {
			const instance = await this.metaService.fetch();

			return {
				maintainerName: instance.maintainerName,
				maintainerEmail: instance.maintainerEmail,
				version: this.config.version,
				name: instance.name,
				shortName: instance.shortName,
				uri: this.config.url,
				description: instance.description,
				langs: instance.langs,
				tosUrl: instance.termsOfServiceUrl,
				repositoryUrl: instance.repositoryUrl,
				feedbackUrl: instance.feedbackUrl,
				impressumUrl: instance.impressumUrl,
				privacyPolicyUrl: instance.privacyPolicyUrl,
				disableRegistration: instance.disableRegistration,
				emailRequiredForSignup: instance.emailRequiredForSignup,
				enableHcaptcha: instance.enableHcaptcha,
				hcaptchaSiteKey: instance.hcaptchaSiteKey,
				enableMcaptcha: instance.enableMcaptcha,
				mcaptchaSiteKey: instance.mcaptchaSitekey,
				mcaptchaInstanceUrl: instance.mcaptchaInstanceUrl,
				enableRecaptcha: instance.enableRecaptcha,
				recaptchaSiteKey: instance.recaptchaSiteKey,
				enableTurnstile: instance.enableTurnstile,
				turnstileSiteKey: instance.turnstileSiteKey,
				swPublickey: instance.swPublicKey,
				themeColor: instance.themeColor,
				mascotImageUrl: instance.mascotImageUrl,
				bannerUrl: instance.bannerUrl,
				serverErrorImageUrl: instance.serverErrorImageUrl,
				notFoundImageUrl: instance.notFoundImageUrl,
				infoImageUrl: instance.infoImageUrl,
				iconUrl: instance.iconUrl,
				app192IconUrl: instance.app192IconUrl,
				app512IconUrl: instance.app512IconUrl,
				backgroundImageUrl: instance.backgroundImageUrl,
				logoImageUrl: instance.logoImageUrl,
				defaultLightTheme: instance.defaultLightTheme,
				defaultDarkTheme: instance.defaultDarkTheme,
				enableEmail: instance.enableEmail,
				enableServiceWorker: instance.enableServiceWorker,
				translatorAvailable: instance.deeplAuthKey != null,
				cacheRemoteFiles: instance.cacheRemoteFiles,
				cacheRemoteSensitiveFiles: instance.cacheRemoteSensitiveFiles,
				pinnedUsers: instance.pinnedUsers,
				hiddenTags: instance.hiddenTags,
				blockedHosts: instance.blockedHosts,
				silencedHosts: instance.silencedHosts,
				sensitiveWords: instance.sensitiveWords,
				prohibitedWords: instance.prohibitedWords,
				preservedUsernames: instance.preservedUsernames,
				hcaptchaSecretKey: instance.hcaptchaSecretKey,
				mcaptchaSecretKey: instance.mcaptchaSecretKey,
				recaptchaSecretKey: instance.recaptchaSecretKey,
				turnstileSecretKey: instance.turnstileSecretKey,
				sensitiveMediaDetection: instance.sensitiveMediaDetection,
				sensitiveMediaDetectionSensitivity: instance.sensitiveMediaDetectionSensitivity,
				setSensitiveFlagAutomatically: instance.setSensitiveFlagAutomatically,
				enableSensitiveMediaDetectionForVideos: instance.enableSensitiveMediaDetectionForVideos,
				proxyAccountId: instance.proxyAccountId,
				summalyProxy: instance.summalyProxy,
				email: instance.email,
				smtpSecure: instance.smtpSecure,
				smtpHost: instance.smtpHost,
				smtpPort: instance.smtpPort,
				smtpUser: instance.smtpUser,
				smtpPass: instance.smtpPass,
				swPrivateKey: instance.swPrivateKey,
				useObjectStorage: instance.useObjectStorage,
				objectStorageBaseUrl: instance.objectStorageBaseUrl,
				objectStorageBucket: instance.objectStorageBucket,
				objectStoragePrefix: instance.objectStoragePrefix,
				objectStorageEndpoint: instance.objectStorageEndpoint,
				objectStorageRegion: instance.objectStorageRegion,
				objectStoragePort: instance.objectStoragePort,
				objectStorageAccessKey: instance.objectStorageAccessKey,
				objectStorageSecretKey: instance.objectStorageSecretKey,
				objectStorageUseSSL: instance.objectStorageUseSSL,
				objectStorageUseProxy: instance.objectStorageUseProxy,
				objectStorageSetPublicRead: instance.objectStorageSetPublicRead,
				objectStorageS3ForcePathStyle: instance.objectStorageS3ForcePathStyle,
				deeplAuthKey: instance.deeplAuthKey,
				deeplIsPro: instance.deeplIsPro,
				enableIpLogging: instance.enableIpLogging,
				enableActiveEmailValidation: instance.enableActiveEmailValidation,
				enableVerifymailApi: instance.enableVerifymailApi,
				verifymailAuthKey: instance.verifymailAuthKey,
				enableTruemailApi: instance.enableTruemailApi,
				truemailInstance: instance.truemailInstance,
				truemailAuthKey: instance.truemailAuthKey,
				enableChartsForRemoteUser: instance.enableChartsForRemoteUser,
				enableChartsForFederatedInstances: instance.enableChartsForFederatedInstances,
				enableServerMachineStats: instance.enableServerMachineStats,
				enableIdenticonGeneration: instance.enableIdenticonGeneration,
				bannedEmailDomains: instance.bannedEmailDomains,
				policies: { ...DEFAULT_POLICIES, ...instance.policies },
				manifestJsonOverride: instance.manifestJsonOverride,
				notesPerOneAd: instance.notesPerOneAd,
			};
		});
	}
}
