minimumReleaseAge: 10080

packages:
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bufferutil
  - cbor-extract
  - esbuild
  - msgpackr-extract
  - sharp
  - utf-8-validate
  - v-code-diff
  - vue-demi

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@swc/core': true
  bufferutil: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  utf-8-validate: true
  v-code-diff: true
  vue-demi: true
