minimumReleaseAge: 1440

packages:
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@swc/core'
  - bufferutil
  - cbor-extract
  - esbuild
  - msgpackr-extract
  - sharp
  - utf-8-validate
  - v-code-diff
  - vue-demi
